In [12]:
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt

In [13]:
def markowitz_weights(covariance, returns, risk_free_rate, inverse_covariance=None):
    mu = returns - risk_free_rate
    if inverse_covariance is None:
        inverse_covariance = np.linalg.inv(covariance)
    numerator = inverse_covariance @ mu
    denomenator = np.sum(numerator)
    return numerator/denomenator

def min_variance_weights(covariance, inverse_covariance=None):
    return markowitz_weights(covariance, np.ones(len(covariance)), 0, inverse_covariance)

def portfolio_std(weights, covariance):
    return np.sqrt(weights @ covariance @ weights)

def sharpe_ratio(risk_free_rate, portfolio_return, standard_deviation):
    return (portfolio_return - risk_free_rate) / standard_deviation

def portfolio_return(returns, weights=None):
    if weights is None:
        n = len(returns)
        weights = np.ones() / n
    return weights @ returns

def return_covmatrix(returns, weights=None):
    if type(weights) == None:
        return np.cov(returns, rowvar=False, ddof=0)
    else:
        # np.cov with weights is similar to this calc
        # demeaned_returns = returns - weights @ returns
        # demeaned_returns.T @ (weights * demeaned_returns.T).T
        return np.cov(returns, aweights=weights, rowvar=False, ddof=0)

In [ ]:
vcv = np.array([
[0.07,    0.052649786,    0.007483315],
[0.052649786,    0.11,    -0.028142495],
[0.007483315,    -0.028142495,    0.08]

]
)
rets = np.array([0.08,    0.15,    0.12])

weights =markowitz_weights(vcv,rets,0.03)

print(sharpe_ratio(0.03, portfolio_return(rets, weights), portfolio_std(weights, vcv)))


w = markowitz_weights(covariance, returns, risk_free_rate)
portfolio_std(weights, covariance)
sharpe_ratio(risk_free_rate, portfolio_return, standard_deviation)

In [7]:
cov = np.array([[0.23, 0.12], [0.12, 0.42]])
print(cov)
w = min_variance_weights(covariance=cov)
print(w)
std = portfolio_std(w, cov)
print(std**2)

[[0.23 0.12]
 [0.12 0.42]]
[0.73170732 0.26829268]
0.20048780487804882


In [8]:
total_port_value = 346262 + 159465
weights = np.array([346262/total_port_value, 159465/total_port_value])
cov = np.array([[0.18**2, 0], [0, 0]])
portfolio_std(weights, cov)

0.12324269813555536

In [9]:
total_port_value = 405458 + 183848
weights = np.array([405458/total_port_value, 183848/total_port_value])
cov = np.array([[0.13**2, 0], [0, 0]])
portfolio_std(weights, cov)

0.08944341309947634

In [22]:
cov_m = return_covmatrix(np.array([-0.02, 0.05, 0.09]), np.array([0.3, 0.5, 0.2]))
print(cov_m)
cov_rh = return_covmatrix(np.array([[-0.04, -0.02], [0.06, 0.05], [0.13, 0.09]]), np.array([0.3, 0.5, 0.2]))
print(cov_rh)
beta = cov_rh/cov_m
print(beta)
capm_r = 0.02 + beta*(portfolio_return(np.array([-0.02, 0.05, 0.09]), np.array([0.3, 0.5, 0.2])) - 0.02)
print(capm_r)

0.001621
[[0.003724 0.002452]
 [0.002452 0.001621]]
[[2.29734732 1.51264651]
 [1.51264651 1.        ]]
[[0.0590549  0.04571499]
 [0.04571499 0.037     ]]



$E_rp = 0.14w_v + 0.04(1-w_v)$

$\sigma_p^2 = w_v^2*0.16^2$

$\frac{1}{x}$


In [4]:
returns = np.array([0.09, 0.06, 0.12])
cov = np.array([[0.13**2, 0.7*0.13*0.17, 0.4*0.13*0.18], [0.7*0.13*0.17, 0.17**2, -0.2*0.17*0.18], [0.4*0.13*0.18, -0.2*0.17*0.18, 0.18**2]])
weights = markowitz_weights(cov, returns, 0.02)

sr = sharpe_ratio(0.02, portfolio_return(returns, weights), portfolio_std(weights, cov))

print(portfolio_return(returns, weights))

0.0988468674839936


In [30]:
# $2736 Situation
# ===============

w1 = 2736*100 - 14949 + 48151
u1 = w1**0.5
print(u1)

# $2885 Situation
# ===============

w2 = 2885*100 - 14949 + 48151 + 22930
u2 = w2**0.5
print(u2)

# $3560 Situation
# ===============

w3 = 3560*100 - 14949 + 48151 + 22930 
u3 = w3**0.5
print(u3)

expected_utility = 0.2*u1 + 0.5*u2 + 0.3*u3
print(expected_utility)

# ================================                  
# No betting

# $2736 Situation
# ===============

w1 = 2736*100 + 48151
u1 = w1**0.5
print(u1)

# $2885 Situation
# ===============

w2 = 2885*100 + 48151 
u2 = w2**0.5
print(u2)

# $3560 Situation
# ===============

w3 = 3560*100 + 48151  
u3 = w3**0.5
print(u3)

expected_utility = 0.2*u1 + 0.5*u2 + 0.3*u3
print(expected_utility)



553.8971023574686
587.0536602389939
641.9750773978691
596.8987738103514
567.2309935114617
580.2163389633215
635.728715727078
594.2729829020765
